# Generated by Django 3.2.7 on 2021-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='icon8image.png', upload_to='images/'),
        ),
    ]
