# Generated by Django 3.2.7 on 2021-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshorts', '0002_post_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='content_link',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='news_author',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='news_publish',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
