# Generated by Django 3.2.7 on 2021-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inshorts', '0005_alter_post_content_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_link',
            field=models.URLField(blank=True),
        ),
    ]
