# Generated by Django 3.2.7 on 2021-09-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inshorts', '0006_alter_post_content_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_link',
        ),
    ]
